name: Deploy House Price MLOps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t rahulsinghdocker1998/house-price-api:latest .

      - name: Push Docker image
        run: |
          docker push rahulsinghdocker1998/house-price-api:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            docker pull rahulsinghdocker1998/house-price-api:latest

            docker stop house-price-api || true
            docker rm house-price-api || true

            docker run -d \
              --name house-price-api \
              -p 8000:8000 \
              -e MLFLOW_TRACKING_URI=http://3.229.3.201:5000 \
              --restart unless-stopped \
              rahulsinghdocker1998/house-price-api:latestname: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t rahulsinghdocker1998/house-price-api:latest .

      - name: Push Docker image
        run: |
          docker push rahulsinghdocker1998/house-price-api:latest